/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppChip: typeof import('./src/components/AppChip.vue')['default']
    AppDialog: typeof import('./src/components/AppDialog.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    AppSelectField: typeof import('./src/components/AppSelectField.vue')['default']
    AppTextField: typeof import('./src/components/AppTextField.vue')['default']
    AppTooltip: typeof import('./src/components/AppTooltip.vue')['default']
  }
}
