/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppCheckbox: typeof import('./src/components/AppCheckbox.vue')['default']
    AppChip: typeof import('./src/components/AppChip.vue')['default']
    AppDialog: typeof import('./src/components/AppDialog.vue')['default']
    AppDropdown: typeof import('./src/components/AppDropdown.vue')['default']
    AppDropdownItem: typeof import('./src/components/AppDropdownItem.vue')['default']
    AppField: typeof import('./src/components/AppField.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    AppLoadingSpinner: typeof import('./src/components/AppLoadingSpinner.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    AppSelectField: typeof import('./src/components/AppSelectField.vue')['default']
    AppTextField: typeof import('./src/components/AppTextField.vue')['default']
    AppTooltip: typeof import('./src/components/AppTooltip.vue')['default']
  }
}
