name: Percy

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install
        run: pnpm i

      - name: Setup Chrome sandbox for Puppeteer
        run: |
          ls -la ~/.cache/puppeteer/chrome/
          cd ~/.cache/puppeteer/chrome/linux-*/chrome-linux64/
          sudo chown root:root chrome_sandbox
          sudo chmod 4755 chrome_sandbox
          sudo cp -p chrome_sandbox /usr/local/sbin/chrome-devel-sandbox
        shell: bash

      - name: Export CHROME_DEVEL_SANDBOX env variable
        run: echo "CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox" >> $GITHUB_ENV
        shell: bash

      - run: pnpm percy exec pnpm run stories:build
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
