name: Visual Regression Testing

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build stories
        run: pnpm stories:build

      - name: Install playwright browsers
        run: pnpm exec playwright install

      - name: Lost Pixel
        run: pnpm lost-pixel
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
          CI_BUILD_ID: ${{ github.run_id }}
          CI_BUILD_NUMBER: ${{ github.run_number }}
          REPOSITORY: ${{ github.repository }}
          COMMIT_REF_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
