name: Percy

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install
        run: pnpm i

      - run: pnpm percy exec pnpm run stories:build -- --no-sandbox
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
